services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - lastfm_pg_volume:/var/lib/postgresql/data

volumes:
  lastfm_pg_volume: {}
